spring:
  application:
    name: blog-dev

  jpa:
    hibernate:
      ddl-auto: update # ??? ??? ??
    show-sql: true # sql? ??? ??
    properties:
      hibernate:
        format_sql: true # sql ??? ??

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
