spring:
  application:
    name: blog-dev
  datasource:
    url: jdbc:h2:file:./data/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # ??? ??? ??
    show-sql: true # sql? ??? ??
    properties:
      hibernate:
        format_sql: true # sql ??? ??
  h2:
    console:
      enabled: true # ????? DB ?? ??

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
