spring:
  application:
    name: blog-dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 실행되는 SQL 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE